name: Feature Request
description: Suggest a feature for VeloraVouchers
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: textarea
    id: problem_solved
    attributes:
      label: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: extra_context
    attributes:
      label: Additional context
    validations:
      required: false
